name: HabitTask
description: Habitask is my Flutter UI design training project focused on developing a modern task management app. Through this project, I enhanced my skills in Flutter by creating an intuitive interface for task tracking and habit formation, featuring custom themes, animations, and responsive design. This project showcases my proficiency in Flutter and my ability to build user-friendly, visually appealing applications.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^2.2.3
  flutter_slidable: ^0.5.7

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - asset/image/

  fonts:
    - family: avenir
      fonts:
        - asset: asset/font/Avenir-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
